apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by Sohrab Khan
  name: web-app
  namespace: default
spec:
  externalIPs:
  - 192.168.1.31
  loadBalancerIP:
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      export: Export
      app: web-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-app
        export: Export
    spec:
      dnsPolicy: Default
      hostNetwork: false
      containers:
        - name: web-app
          image: web_app:v2
          imagePullPolicy: Always
          ports:
            - name: web-app-port
              containerPort: 8080
              protocol: TCP
